/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author This PC
 */
public class Dashboard_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Login_Employee
     */
    public Dashboard_Employee() {
        initComponents();
        date();
        time();
    }
    public void date(){
        Date d=new Date();
        SimpleDateFormat format=new SimpleDateFormat("YYYY-MM-dd");
        
        String date= format.format(d);
        dateLBL.setText(date);
    
    }
    
     public void time(){
         new Timer(0, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 Date d2=new Date();
                 SimpleDateFormat format=new SimpleDateFormat("hh:mm:ss a");
                 String time=format.format(d2);
                 timeLBL.setText(time);
                 
                 
             }
         }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exitLBL = new javax.swing.JLabel();
        addempLBL = new javax.swing.JLabel();
        viewempLBL = new javax.swing.JLabel();
        emploginLBL = new javax.swing.JLabel();
        backLBL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        timeLBL = new javax.swing.JLabel();
        dateLBL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLBL.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        exitLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/power.png"))); // NOI18N
        exitLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLBLMouseClicked(evt);
            }
        });
        getContentPane().add(exitLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, -1, -1));

        addempLBL.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        addempLBL.setForeground(new java.awt.Color(255, 255, 255));
        addempLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/plus.png"))); // NOI18N
        addempLBL.setText("Add Emplyee");
        getContentPane().add(addempLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        viewempLBL.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        viewempLBL.setForeground(new java.awt.Color(255, 255, 255));
        viewempLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/file.png"))); // NOI18N
        viewempLBL.setText("View Emplyees ");
        getContentPane().add(viewempLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        emploginLBL.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        emploginLBL.setForeground(new java.awt.Color(255, 255, 255));
        emploginLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/login (1).png"))); // NOI18N
        emploginLBL.setText("Emplyee Login");
        emploginLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emploginLBLMouseClicked(evt);
            }
        });
        getContentPane().add(emploginLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 50));

        backLBL.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        backLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backward.png"))); // NOI18N
        backLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBLMouseClicked(evt);
            }
        });
        getContentPane().add(backLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel9.setBackground(new java.awt.Color(102, 0, 204));
        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/tv.png"))); // NOI18N
        jLabel9.setText("TASA Cinema");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 130));

        timeLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        timeLBL.setForeground(new java.awt.Color(255, 255, 51));
        timeLBL.setText("0");
        getContentPane().add(timeLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 200, -1));

        dateLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        dateLBL.setForeground(new java.awt.Color(255, 255, 51));
        dateLBL.setText("0");
        getContentPane().add(dateLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/papers.co-si40-blue-saturday-night-live-gradation-blur-29-wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 910, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBLMouseClicked
        // TODO add your handling code here:
        
        Login_Admin back1=new Login_Admin();
        back1.setVisible(true);
        super.dispose();
        
    }//GEN-LAST:event_backLBLMouseClicked

    private void exitLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLBLMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLBLMouseClicked

    private void emploginLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emploginLBLMouseClicked
        // TODO add your handling code here:
        
        Login_Employee go4= new Login_Employee();
        go4.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_emploginLBLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Employee().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addempLBL;
    private javax.swing.JLabel backLBL;
    private javax.swing.JLabel dateLBL;
    private javax.swing.JLabel emploginLBL;
    private javax.swing.JLabel exitLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JLabel viewempLBL;
    // End of variables declaration//GEN-END:variables
}
