/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author This PC
 */
public class Dashboard_Main extends javax.swing.JFrame {

    /**
     * Creates new form MainDashboard
     */
    public Dashboard_Main() {
        initComponents();
        date();
        time();
    }
    public void date(){
        Date d=new Date();
        SimpleDateFormat format=new SimpleDateFormat("YYYY-MM-dd");
        
        String date= format.format(d);
        dateLBL.setText(date);
    
    }
    
     public void time(){
         new Timer(0, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 Date d2=new Date();
                 SimpleDateFormat format=new SimpleDateFormat("hh:mm:ss a");
                 String time=format.format(d2);
                 timeLBL.setText(time);
                 
                 
             }
         }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewmovieBTN = new javax.swing.JButton();
        viewreservationBTN = new javax.swing.JButton();
        addreservationBTN = new javax.swing.JButton();
        cusregBTN = new javax.swing.JButton();
        addmovieBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        exitLBL = new javax.swing.JLabel();
        backLBL = new javax.swing.JLabel();
        viewpaymentBTN = new javax.swing.JButton();
        viewcustomerBTN = new javax.swing.JButton();
        timeLBL = new javax.swing.JLabel();
        dateLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewmovieBTN.setBackground(new java.awt.Color(51, 0, 51));
        viewmovieBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        viewmovieBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewmovieBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/video-player.png"))); // NOI18N
        viewmovieBTN.setText("View Movie");
        viewmovieBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmovieBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewmovieBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 50));

        viewreservationBTN.setBackground(new java.awt.Color(51, 0, 51));
        viewreservationBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        viewreservationBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewreservationBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/booking (1).png"))); // NOI18N
        viewreservationBTN.setText("View Reservation");
        viewreservationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreservationBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewreservationBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 310, 50));

        addreservationBTN.setBackground(new java.awt.Color(51, 0, 51));
        addreservationBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        addreservationBTN.setForeground(new java.awt.Color(255, 255, 255));
        addreservationBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/booking.png"))); // NOI18N
        addreservationBTN.setText("Add Reservation");
        addreservationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreservationBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addreservationBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 280, 50));

        cusregBTN.setBackground(new java.awt.Color(51, 0, 51));
        cusregBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        cusregBTN.setForeground(new java.awt.Color(255, 255, 255));
        cusregBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/customer-service.png"))); // NOI18N
        cusregBTN.setText("Customer Registration");
        cusregBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusregBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cusregBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 360, 50));

        addmovieBTN.setBackground(new java.awt.Color(51, 0, 51));
        addmovieBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        addmovieBTN.setForeground(new java.awt.Color(255, 255, 255));
        addmovieBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/plus.png"))); // NOI18N
        addmovieBTN.setText("Add Movie");
        addmovieBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmovieBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addmovieBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 50));

        jLabel7.setBackground(new java.awt.Color(102, 0, 204));
        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home (2).png"))); // NOI18N
        jLabel7.setText("Dashboard");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 330, 90));

        exitLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/power.png"))); // NOI18N
        exitLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLBLMouseClicked(evt);
            }
        });
        getContentPane().add(exitLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, -1, -1));

        backLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backward.png"))); // NOI18N
        backLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBLMouseClicked(evt);
            }
        });
        getContentPane().add(backLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        viewpaymentBTN.setBackground(new java.awt.Color(51, 0, 51));
        viewpaymentBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        viewpaymentBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewpaymentBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/pay.png"))); // NOI18N
        viewpaymentBTN.setText("View Payment");
        viewpaymentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpaymentBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewpaymentBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 260, 50));

        viewcustomerBTN.setBackground(new java.awt.Color(51, 0, 51));
        viewcustomerBTN.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        viewcustomerBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewcustomerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/booking (1).png"))); // NOI18N
        viewcustomerBTN.setText("View Customer");
        viewcustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcustomerBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewcustomerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 260, 50));

        timeLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        timeLBL.setForeground(new java.awt.Color(255, 255, 51));
        timeLBL.setText("0");
        getContentPane().add(timeLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, -1));

        dateLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        dateLBL.setForeground(new java.awt.Color(255, 255, 51));
        dateLBL.setText("0");
        getContentPane().add(dateLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/GRADIENT-3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 900, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addmovieBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmovieBTNActionPerformed
        // TODO add your handling code here:

        Add_Movie go =new Add_Movie();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_addmovieBTNActionPerformed

    private void viewmovieBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmovieBTNActionPerformed
        // TODO add your handling code here:
        View_Movie go= new View_Movie();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_viewmovieBTNActionPerformed

    private void addreservationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreservationBTNActionPerformed
        // TODO add your handling code here:
     
        Seat_Reserving_Admin go =new Seat_Reserving_Admin();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_addreservationBTNActionPerformed

    private void viewreservationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreservationBTNActionPerformed
        // TODO add your handling code here:
        View_Reservation go6=new View_Reservation();
        go6.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_viewreservationBTNActionPerformed

    private void cusregBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusregBTNActionPerformed
        // TODO add your handling code here:
        Add_Customer_Admin go= new Add_Customer_Admin();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_cusregBTNActionPerformed

    private void backLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBLMouseClicked
        // TODO add your handling code here:
        
        Login_Employee back3=new Login_Employee();
        back3.setVisible(true);
        super.dispose();
        
    }//GEN-LAST:event_backLBLMouseClicked

    private void exitLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLBLMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitLBLMouseClicked

    private void viewcustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcustomerBTNActionPerformed
        // TODO add your handling code here:
        View_Customers back4=new View_Customers();
        back4.setVisible(true);
        super.dispose();
        
    }//GEN-LAST:event_viewcustomerBTNActionPerformed

    private void viewpaymentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpaymentBTNActionPerformed
        // TODO add your handling code here:
        View_Payment go5=new View_Payment();
        go5.setVisible(true);
        super.dispose();
        
        
    }//GEN-LAST:event_viewpaymentBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmovieBTN;
    private javax.swing.JButton addreservationBTN;
    private javax.swing.JLabel backLBL;
    private javax.swing.JButton cusregBTN;
    private javax.swing.JLabel dateLBL;
    private javax.swing.JLabel exitLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JButton viewcustomerBTN;
    private javax.swing.JButton viewmovieBTN;
    private javax.swing.JButton viewpaymentBTN;
    private javax.swing.JButton viewreservationBTN;
    // End of variables declaration//GEN-END:variables
}
