/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MovieDeleteController;
import Controller.Update_Controller;
import Model.DBSearchMovie;
import Model.DbConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author This PC
 */
public class View_Movie extends javax.swing.JFrame {

    /**
     * Creates new form View_Movie
     */
    public View_Movie() {
        initComponents();
        date();
        time();
    }
    public void date(){
        Date d=new Date();
        SimpleDateFormat format=new SimpleDateFormat("YYYY-MM-dd");
        
        String date= format.format(d);
        dateLBL.setText(date);
    
    }
    
     public void time(){
         new Timer(0, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 Date d2=new Date();
                 SimpleDateFormat format=new SimpleDateFormat("hh:mm:ss a");
                 String time=format.format(d2);
                 timeLBL.setText(time);
                 
                 
             }
         }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        backLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTBL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateLBL = new javax.swing.JLabel();
        timeLBL = new javax.swing.JLabel();
        exitLBL = new javax.swing.JLabel();
        updateLBL = new javax.swing.JLabel();
        deleteJP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        deleteTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        updateJP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        updateBTN = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        midTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        timeCMB = new javax.swing.JComboBox();
        displayLBL = new javax.swing.JLabel();
        deleteLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(102, 0, 204));
        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/tv.png"))); // NOI18N
        jLabel6.setText("TASA Cinema");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 130));

        backLBL.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        backLBL.setForeground(new java.awt.Color(255, 255, 255));
        backLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backward.png"))); // NOI18N
        backLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBLMouseClicked(evt);
            }
        });
        getContentPane().add(backLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 40, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        viewTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Index", "Movie_Name", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTBL);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Movie List");

        dateLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        dateLBL.setForeground(new java.awt.Color(255, 255, 51));
        dateLBL.setText("0");

        timeLBL.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        timeLBL.setForeground(new java.awt.Color(255, 255, 51));
        timeLBL.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLBL)
                    .addComponent(dateLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 580, 230));

        exitLBL.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        exitLBL.setForeground(new java.awt.Color(255, 255, 255));
        exitLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/power.png"))); // NOI18N
        exitLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLBLMouseClicked(evt);
            }
        });
        getContentPane().add(exitLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 40, 50));

        updateLBL.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        updateLBL.setForeground(new java.awt.Color(255, 255, 255));
        updateLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/update.png"))); // NOI18N
        updateLBL.setText("update Movie");
        updateLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateLBLMouseClicked(evt);
            }
        });
        getContentPane().add(updateLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, 50));

        deleteJP.setBackground(new java.awt.Color(51, 0, 0));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Movie index to be Deleted : - ");

        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/delete.png"))); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/delete (1).png"))); // NOI18N

        javax.swing.GroupLayout deleteJPLayout = new javax.swing.GroupLayout(deleteJP);
        deleteJP.setLayout(deleteJPLayout);
        deleteJPLayout.setHorizontalGroup(
            deleteJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteJPLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTF, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteJPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(deleteJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteJPLayout.createSequentialGroup()
                                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteJPLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(172, 172, 172))))))
        );
        deleteJPLayout.setVerticalGroup(
            deleteJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteJPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(deleteJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBTN)
                .addGap(15, 15, 15))
        );

        getContentPane().add(deleteJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 580, 280));

        updateJP.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/updated.png"))); // NOI18N

        updateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/update.png"))); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 153));
        jLabel13.setText("New Time         : -");

        jLabel11.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 153));
        jLabel11.setText("New Name        : -");

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 153));
        jLabel7.setText("Movie_ID          : -");

        midTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midTFActionPerformed(evt);
            }
        });

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        timeCMB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        timeCMB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "1.30p.m - 3.30p.m", "4.30p.m - 6.30p.m", "7.30p.m - 9.30p.m" }));
        timeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeCMBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateJPLayout = new javax.swing.GroupLayout(updateJP);
        updateJP.setLayout(updateJPLayout);
        updateJPLayout.setHorizontalGroup(
            updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateJPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(21, 21, 21)
                .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBTN)
                    .addGroup(updateJPLayout.createSequentialGroup()
                        .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(midTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(timeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        updateJPLayout.setVerticalGroup(
            updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateJPLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateJPLayout.createSequentialGroup()
                        .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(midTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(updateBTN)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(updateJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 580, 280));

        displayLBL.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        displayLBL.setForeground(new java.awt.Color(255, 255, 255));
        displayLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/video-player.png"))); // NOI18N
        displayLBL.setText("Display Movies");
        displayLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayLBLMouseClicked(evt);
            }
        });
        getContentPane().add(displayLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 50));

        deleteLBL.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        deleteLBL.setForeground(new java.awt.Color(255, 255, 255));
        deleteLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/delete.png"))); // NOI18N
        deleteLBL.setText("Delete Movie");
        deleteLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLBLMouseClicked(evt);
            }
        });
        getContentPane().add(deleteLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/GRADIENT-3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBLMouseClicked
        // TODO add your handling code here:

        Dashboard_Main go= new Dashboard_Main();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backLBLMouseClicked

    public void clearfield(){
        
        midTF.setText("");
        nameTF.setText("");
        timeCMB.setSelectedItem("Null");
        
    }
    
    private void exitLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLBLMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitLBLMouseClicked

    private void updateLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLBLMouseClicked
        // TODO add your handling code here:
        updateJP.setVisible(true);
        deleteJP.setVisible(false);
        
        
    }//GEN-LAST:event_updateLBLMouseClicked

    private void displayLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayLBLMouseClicked
        // TODO add your handling code here:
        ResultSet r = new DBSearchMovie().searchMovie();
        DefaultTableModel dtm = (DefaultTableModel)viewTBL.getModel();
        dtm.setRowCount(0);
        try {
            Vector v;
            while (r.next()){
                v=new Vector();
                v.add(r.getString("m_id"));
                v.add(r.getString("m_name"));
                v.add(r.getString("m_time"));
                dtm.addRow(v);
            }
            DbConnection.closeCon();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_displayLBLMouseClicked

    private void deleteLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLBLMouseClicked
        // TODO add your handling code here:
        
        deleteJP.setVisible(true);
        updateJP.setVisible(false);
       
    }//GEN-LAST:event_deleteLBLMouseClicked

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        
         String id=deleteTF.getText();
        MovieDeleteController.movie(id);
        deleteTF.setText("");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void midTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midTFActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void timeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeCMBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_timeCMBActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
        int id= Integer.parseInt(midTF.getText());
        String name=nameTF.getText();
        String time=timeCMB.getSelectedItem().toString();
        
        Update_Controller.updateMovie(id, name, time);
        
        clearfield();
    }//GEN-LAST:event_updateBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLBL;
    private javax.swing.JLabel dateLBL;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JPanel deleteJP;
    private javax.swing.JLabel deleteLBL;
    private javax.swing.JTextField deleteTF;
    private javax.swing.JLabel displayLBL;
    private javax.swing.JLabel exitLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField midTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JComboBox timeCMB;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JButton updateBTN;
    private javax.swing.JPanel updateJP;
    private javax.swing.JLabel updateLBL;
    private javax.swing.JTable viewTBL;
    // End of variables declaration//GEN-END:variables
}
